# -*- coding: utf-8 -*-
"""Data_Analysis_and_Machine_Learning_Modeling_for_Insurance_Customer_Classification (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0SF3Hn3ZCISIm5kg8AHKecT5vqGkTAc

Data Analysis and Machine Learning Modeling for Insurance Customer Classification

## Data Understanding

**Load data di Google Colab**

*dataset berikut : https://drive.google.com/file/d/15fPi0IimBYIsR_42dywgGKJqiEhasZ4F/view?usp=sharing*
"""

import pandas as pd

url = 'https://drive.google.com/uc?id=15fPi0IimBYIsR_42dywgGKJqiEhasZ4F'
data = pd.read_csv(url)

# Tampilkan 5 data teratas
data.head()

"""Insight:

**Telaah Data**

Cek struktur dan tipe data
"""

data.info()

"""Insight:

Cek statistik deskriptif
"""

data.describe()

"""Insight:

Cek Missing Values
"""

data.isnull().sum()

"""Insight:

Cek Outlier pakai Boxplot
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(15, 8))
sns.boxplot(data=data[['CreditScore', 'Age', 'Balance', 'EstimatedSalary']])
plt.title("Boxplot untuk Deteksi Outlier")
plt.show()

"""Insight:

Cek Anomali Data
"""

# Distribusi target
data['Exited'].value_counts(normalize=True)

# Cek nilai unik untuk fitur penting
print(data['Geography'].value_counts())
print(data['Gender'].value_counts())

"""## Data Preproccesing

Membersihkan Data

Drop kolom tidak relevan
"""

# Kolom RowNumber, CustomerId, dan Surname tidak berpengaruh terhadap prediksi
data_cleaned = data.drop(columns=['RowNumber', 'CustomerId', 'Surname'])

"""Cek ulang missing value dan duplikat"""

# Missing value
print(data_cleaned.isnull().sum())

# Duplikat
print(data_cleaned.duplicated().sum())

"""Handling outlier bisa menggunakan IQR/clip/normalisasi"""

# Batasi outlier kolom 'Age' berdasarkan IQR
Q1 = data_cleaned['Age'].quantile(0.25)
Q3 = data_cleaned['Age'].quantile(0.75)
IQR = Q3 - Q1
data_cleaned = data_cleaned[(data_cleaned['Age'] >= Q1 - 1.5 * IQR) & (data_cleaned['Age'] <= Q3 + 1.5 * IQR)]

"""### Exploratory Data Analysis (EDA)

Korelasi numerik terhadap target Exited
"""

# Select only numeric columns for correlation calculation
numeric_data_cleaned = data_cleaned.select_dtypes(include=['number'])

plt.figure(figsize=(10,6))
sns.heatmap(numeric_data_cleaned.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap (Numeric Columns Only)')
plt.show()

"""Visualisasi distribusi churn per fitur"""

# Distribusi Age vs Churn
sns.boxplot(x='Exited', y='Age', data=data_cleaned)
plt.title('Distribusi Age terhadap Churn')
plt.show()

"""Feature Importance (pakai Random Forest sebagai baseline):"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

# Encode categorical: Geography, Gender
data_encoded = data_cleaned.copy()
le_geo = LabelEncoder()
le_gender = LabelEncoder()
data_encoded['Geography'] = le_geo.fit_transform(data_encoded['Geography'])
data_encoded['Gender'] = le_gender.fit_transform(data_encoded['Gender'])

# Split fitur dan label
X = data_encoded.drop(columns='Exited')
y = data_encoded['Exited']

# Random Forest
rf = RandomForestClassifier()
rf.fit(X, y)

# Visualisasi Feature Importance
feat_imp = pd.Series(rf.feature_importances_, index=X.columns)
feat_imp.sort_values().plot(kind='barh', title='Feature Importance')
plt.show()

"""Menentukan Label Data"""

# Cek distribusi label
data_cleaned['Exited'].value_counts(normalize=True)

"""## Modelling

Pisahkan fitur dan label
"""

X = data_encoded.drop(columns='Exited')
y = data_encoded['Exited']

"""Split Data (75% training, 25% testing)"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y)

# Menampilkan distribusi label sebelum dan sesudah split
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# Distribusi label di data awal
sns.countplot(x=y, ax=axes[0])
axes[0].set_title('Distribusi Label (Original)')
axes[0].bar_label(axes[0].containers[0])

# Distribusi label di data training
sns.countplot(x=y_train, ax=axes[1])
axes[1].set_title('Distribusi Label (Training)')
axes[1].bar_label(axes[1].containers[0])

# Distribusi label di data testing
sns.countplot(x=y_test, ax=axes[2])
axes[2].set_title('Distribusi Label (Testing)')
axes[2].bar_label(axes[2].containers[0])

plt.tight_layout()
plt.show()

# Menampilkan proporsi dalam persentase
print("Proporsi label pada dataset asli:")
print(y.value_counts(normalize=True) * 100)

print("\nProporsi label pada data training:")
print(y_train.value_counts(normalize=True) * 100)

print("\nProporsi label pada data testing:")
print(y_test.value_counts(normalize=True) * 100)

"""Model Decision Tree Classifier"""

from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

"""k-Nearest Neighbors (k-NN) Classifier"""

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train_knn, X_test_knn, y_train_knn, y_test_knn = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y)

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_knn, y_train_knn)
y_pred_knn = knn_model.predict(X_test_knn)

"""## Evaluation Model

Import Metric & Evaluasi Decision Tree
"""

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("=== Decision Tree ===")
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))
print("Akurasi:", accuracy_score(y_test, y_pred_dt))

"""Evaluasi k-NN"""

print("=== k-NN ===")
print(confusion_matrix(y_test_knn, y_pred_knn))
print(classification_report(y_test_knn, y_pred_knn))
print("Akurasi:", accuracy_score(y_test_knn, y_pred_knn))

"""Perbandingan Model"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Hitung metrik untuk Decision Tree
dt_accuracy = accuracy_score(y_test, y_pred_dt)
dt_precision = precision_score(y_test, y_pred_dt)
dt_recall = recall_score(y_test, y_pred_dt)
dt_f1 = f1_score(y_test, y_pred_dt)

# Hitung metrik untuk k-NN
knn_accuracy = accuracy_score(y_test_knn, y_pred_knn)
knn_precision = precision_score(y_test_knn, y_pred_knn)
knn_recall = recall_score(y_test_knn, y_pred_knn)
knn_f1 = f1_score(y_test_knn, y_pred_knn)

# Tampilkan hasil perbandingan
print("=== Perbandingan Model ===")
print(f"Decision Tree -> Accuracy: {dt_accuracy:.2f}, Precision: {dt_precision:.2f}, Recall: {dt_recall:.2f}, F1-Score: {dt_f1:.2f}")
print(f"k-NN          -> Accuracy: {knn_accuracy:.2f}, Precision: {knn_precision:.2f}, Recall: {knn_recall:.2f}, F1-Score: {knn_f1:.2f}")

# Tentukan model terbaik berdasarkan F1-Score
if dt_f1 > knn_f1:
    print("\n Model terbaik adalah: Decision Tree (berdasarkan F1-Score lebih tinggi)")
elif knn_f1 > dt_f1:
    print("\n Model terbaik adalah: k-NN (berdasarkan F1-Score lebih tinggi)")
else:
    print("\n Kedua model memiliki F1-Score yang sama, bisa dipilih berdasarkan kebutuhan bisnis.")



